# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_id',
        ),
    ]
