# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='address_line2',
            new_name='address_line_2',
        ),
    ]
