# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171206_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='aw_image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
