# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:38
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171207_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='products.Category'),
        ),
    ]
