# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171211_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aw_deep_link',
            new_name='merchant_deep_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant_category',
        ),
    ]
