# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 15:20
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180111_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='products.Category'),
        ),
    ]
